In [1]:
import numpy as np

In [2]:
def crtbp(popsize, chromlen):
    return np.random.randint(0, 2, size=(popsize, chromlen))

In [3]:
popsize = 4
chromlen = 4
chrom = crtbp(popsize,chromlen)
print(chrom)

[[1 1 0 1]
 [1 0 1 1]
 [1 1 1 1]
 [1 1 1 0]]


In [4]:
def bs2rv(chrom, lb, ub):
    popsize, chromlen = chrom.shape
    phen = np.zeros(popsize)
    delta = (ub - lb)/(2**chromlen - 1)
    for i in range(popsize):
        phen[i] = lb + np.sum(chrom[i, :] * 2**(np.arange(chromlen - 1, -1, -1))) * delta
    return phen

In [5]:
lb = 0
ub = 30
phen = bs2rv(chrom, lb, ub)
print(phen)

[26. 22. 30. 28.]


In [6]:
def select(chrom, fitness, nsel):
    popsize, chromlen = chrom.shape
    fitness_ratio = np.cumsum(fitness) / np.sum(fitness)
    fitness_interval = np.r_[0, fitness_ratio]
    random_num = np.random.rand(nsel)
    print(random_num)
    new_chrom = np.zeros((nsel, chromlen), dtype=int)
    for i in range(nsel):
        ind = np.logical_and(fitness_interval[:-1] <= random_num[i], 
                             fitness_interval[1:] > random_num[i])
        new_chrom[i, :] = chrom[ind, :]
    return new_chrom

In [7]:
fitness_fun = lambda x: x*x
fitness = fitness_fun(phen)
print(fitness)

[676. 484. 900. 784.]


In [8]:
ps = 0.7
nsel = min(int(np.round(popsize * ps)), popsize)
print(nsel)

3


In [9]:
print(chrom)
new_chrom = select(chrom, fitness, nsel)
print(new_chrom)

[[1 1 0 1]
 [1 0 1 1]
 [1 1 1 1]
 [1 1 1 0]]
[0.81466533 0.81649983 0.83114385]
[[1 1 1 0]
 [1 1 1 0]
 [1 1 1 0]]


In [10]:
def crossover(chrom, pc):
    popsize, chromlen = chrom.shape
    new_chrom = np.zeros_like(chrom)
    xops = popsize // 2
    if popsize % 2:
        new_chrom[-1, :] = chrom[-1, :]
    else:
        for i in range(0, xops + 1, 2):
            if np.random.rand() <= pc:
                cross_point = np.random.randint(0, chromlen)
                print(cross_point)
                new_chrom[i, :cross_point + 1] = chrom[i, :cross_point + 1]
                new_chrom[i, cross_point + 1:] = chrom[i + 1, cross_point + 1:]
                new_chrom[i + 1, :cross_point + 1] = chrom[i + 1, :cross_point + 1]
                new_chrom[i + 1, cross_point + 1:] = chrom[i, cross_point + 1:]
            else:
                new_chrom[i, :] = chrom[i, :]
                new_chrom[i + 1, :] = chrom[i + 1, :]
    return new_chrom

In [11]:
pc = 1
print(chrom)
new_chrom = crossover(chrom, pc)
print(new_chrom)

[[1 1 0 1]
 [1 0 1 1]
 [1 1 1 1]
 [1 1 1 0]]
0
2
[[1 0 1 1]
 [1 1 0 1]
 [1 1 1 0]
 [1 1 1 1]]


In [12]:
def mutation(chrom, pm):
    popsize, chromlen = chrom.shape
    new_chrom = chrom.copy()
    ind = np.random.rand(popsize, chromlen) <= pm
    print(ind)
    new_chrom[ind] = (new_chrom[ind] + 1) % 2
    return new_chrom

In [13]:
pm = 1
print(chrom)
new_chrom = mutation(chrom, pm)
print(new_chrom)

[[1 1 0 1]
 [1 0 1 1]
 [1 1 1 1]
 [1 1 1 0]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[0 0 1 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 0 0 1]]
